### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by MorganMcmillan** [eldexterr/pmblackpit#2]
![Screenshot 2023-07-19 173158](https://github.com/eldexterr/pmblackpit/assets/135075054/ae2de3ef-bd60-48b8-8b7c-6ddc994aab66)

**Comment by eldexterr** [comment]
PJ64 + Windows 11 crash

**Comment by eldexterr** [comment]
PJ64 + Windows 11 crash

**Comment by MorganMcmillan** [comment]
It keeps happening
[image: Screenshot 2023-07-19 195448.png]

**Comment by MorganMcmillan** [comment]
How do I fix this?
